# PowerShell script để test nhanh Review APIs
# Sử dụng PowerShell v5.1

param(
    [string]$BaseUrl = $(if ($env:API_URL) { $env:API_URL } else { 'http://localhost:5002/api' }),
    [string]$Token = '',
    [int]$UserId = 0,
    [int]$OrderId = 0,
    [int]$ProductId = 0
)

function Get-AuthHeaders {
    param($token)
    $headers = @{ 'Content-Type' = 'application/json' }
    if ($token -and $token.Trim() -ne '') { $headers['Authorization'] = "Bearer $token" }
    return $headers
}

Write-Host "BaseUrl: $BaseUrl"

$headers = Get-AuthHeaders -token $Token

# 1) Lấy đánh giá theo sản phẩm
if ($ProductId -gt 0) {
    Write-Host "`n==> GET /products/$ProductId/reviews"
    try {
        $res = Invoke-RestMethod -Uri "$BaseUrl/products/$ProductId/reviews" -Method Get -Headers $headers -ErrorAction Stop
        Write-Host "Status: Success"
        $res | ConvertTo-Json -Depth 5 | Write-Host
    } catch {
        Write-Host "Error fetching reviews: $_"
    }
} else {
    Write-Host "Skipping product reviews (ProductId not provided)"
}

# 2) Lấy danh sách sản phẩm có thể đánh giá trong đơn hàng
if ($OrderId -gt 0 -and $UserId -gt 0) {
    Write-Host "`n==> GET /reviews/order/$OrderId/user/$UserId/products"
    try {
        $res = Invoke-RestMethod -Uri "$BaseUrl/reviews/order/$OrderId/user/$UserId/products" -Method Get -Headers $headers -ErrorAction Stop
        Write-Host "Status: Success"
        $res | ConvertTo-Json -Depth 5 | Write-Host
    } catch {
        Write-Host "Error fetching order products for review: $_"
    }
} else {
    Write-Host "Skipping order-products for review (OrderId or UserId not provided)"
}

# 3) Tạo đánh giá cho sản phẩm trong đơn hàng
if ($OrderId -gt 0 -and $UserId -gt 0 -and $ProductId -gt 0) {
    Write-Host "`n==> POST /reviews/order/$OrderId/product/$ProductId/user/$UserId"
    $body = @{ noiDung = 'Test review generated by PowerShell script. Nội dung phải >=10 ký tự.'; danhGiaSao = 5 } | ConvertTo-Json
    try {
        $res = Invoke-RestMethod -Uri "$BaseUrl/reviews/order/$OrderId/product/$ProductId/user/$UserId" -Method Post -Headers $headers -Body $body -ErrorAction Stop
        Write-Host "Create review response:"
        $res | ConvertTo-Json -Depth 5 | Write-Host
    } catch {
        Write-Host "Error creating order review: $_"
    }
} else {
    Write-Host "Skipping create order review (OrderId/UserId/ProductId not provided)"
}

Write-Host "`nDone."
